export const apiEndpoints = [
  {
    category: "🔐 احراز هویت",
    id: "auth",
    items: [
      {
        method: "POST",
        path: "/user/get-otp",
        title: "دریافت کد OTP",
        description: "ارسال کد یکبار مصرف به شماره موبایل کاربر",
        body: { phoneNumber: "09123456789" },
        response: {
          statusCode: 200,
          data: {
            message: "کد تائید برای شماره موبایل ۰۹۱۲۳۴۵۶۷۸۹ ارسال گردید",
            expiresIn: 90000,
            phoneNumber: "09123456789",
          },
        },
        errors: ["400 - شماره موبایل معتبر نیست", "401 - ورود انجام نشد"],
      },
      {
        method: "POST",
        path: "/user/check-otp",
        title: "تایید کد OTP",
        description: "بررسی صحت کد OTP و ورود کاربر به سیستم",
        body: { phoneNumber: "09123456789", otp: "123456" },
        response: {
          statusCode: 200,
          data: {
            message: "کد تایید شد، خوش آمدید",
            user: { _id: "...", name: "علی احمدی", role: "FREELANCER" },
          },
        },
        errors: ["400 - کد صحیح نیست", "404 - کاربر یافت نشد"],
      },
      {
        method: "POST",
        path: "/user/complete-profile",
        title: "تکمیل پروفایل",
        description: "تکمیل اطلاعات پروفایل کاربر پس از ورود اولیه",
        auth: true,
        body: {
          name: "علی احمدی",
          email: "ali@example.com",
          role: "FREELANCER",
        },
        response: {
          statusCode: 200,
          data: { message: "اطلاعات با موفقیت تکمیل شد" },
        },
        errors: ["400 - ایمیل تکراری", "403 - شماره تایید نشده"],
      },
      {
        method: "PATCH",
        path: "/user/update",
        title: "بروزرسانی پروفایل",
        description: "ویرایش اطلاعات پروفایل کاربر",
        auth: true,
        body: {
          name: "علی احمدی",
          email: "ali@example.com",
          biography: "توضیحات",
        },
        response: { statusCode: 200, data: { message: "اطلاعات آپدیت شد" } },
      },
      {
        method: "GET",
        path: "/user/profile",
        title: "دریافت پروفایل",
        description: "دریافت اطلاعات پروفایل کاربر جاری",
        auth: true,
        response: {
          statusCode: 200,
          data: {
            user: { _id: "...", name: "علی احمدی", email: "ali@example.com" },
          },
        },
      },
      {
        method: "GET",
        path: "/user/refresh-token",
        title: "تازه‌سازی توکن",
        description: "دریافت accessToken جدید با استفاده از refreshToken",
        response: { StatusCode: 200, data: { user: "..." } },
      },
      {
        method: "POST",
        path: "/user/logout",
        title: "خروج از حساب",
        description: "خروج کاربر و حذف توکن‌ها از سیستم",
        response: { StatusCode: 200, roles: null, auth: false },
      },
    ],
  },
  {
    category: "📂 دسته‌بندی‌ها",
    id: "category",
    items: [
      {
        method: "GET",
        path: "/category/list",
        title: "لیست دسته‌بندی‌ها",
        description: "دریافت تمام دسته‌بندی‌ها با امکان فیلتر",
        params: "هر فیلد از مدل Category",
        response: {
          statusCode: 200,
          data: {
            categories: [
              {
                _id: "...",
                title: "برنامه‌نویسی",
                englishTitle: "programming",
              },
            ],
          },
        },
      },
      {
        method: "GET",
        path: "/category/:id",
        title: "جزئیات دسته‌بندی",
        description: "دریافت اطلاعات یک دسته‌بندی خاص با ID",
        response: {
          statusCode: 200,
          data: { category: { _id: "...", title: "برنامه‌نویسی" } },
        },
        errors: ["400 - دسته بندی وجود ندارد"],
      },
    ],
  },
  {
    category: "🎯 پروژه‌ها",
    id: "project",
    items: [
      {
        method: "GET",
        path: "/project/list",
        title: "لیست پروژه‌ها",
        description:
          "دریافت لیست تمام پروژه‌ها با قابلیت جستجو و فیلتر پیشرفته",
        auth: true,
        params:
          "search, category, status (OPEN/CLOSED), sort (latest/earliest)",
        response: {
          statusCode: 200,
          data: {
            projects: [
              {
                _id: "...",
                title: "توسعه وب‌سایت",
                budget: 50000000,
                status: "OPEN",
              },
            ],
          },
        },
      },
      {
        method: "GET",
        path: "/project/owner-projects",
        title: "پروژه‌های کارفرما",
        description: "دریافت لیست پروژه‌های ایجاد شده توسط کارفرما",
        auth: true,
        role: "OWNER",
        params: "search, category, sort",
      },
      {
        method: "POST",
        path: "/project/add",
        title: "ایجاد پروژه جدید",
        description: "ثبت پروژه جدید توسط کارفرما",
        auth: true,
        role: "OWNER",
        body: {
          title: "توسعه اپلیکیشن",
          description: "توضیحات پروژه",
          tags: ["react", "nodejs"],
          category: "categoryId",
          budget: 100000000,
          deadline: "2024-12-31",
        },
        response: { statusCode: 201, data: { message: "پروژه ایجاد شد" } },
        errors: ["500 - پروژه ثبت نشد"],
      },
      {
        method: "GET",
        path: "/project/:id",
        title: "جزئیات پروژه",
        description: "دریافت اطلاعات کامل یک پروژه شامل پیشنهادها",
        auth: true,
        response: {
          statusCode: 200,
          data: { project: { _id: "...", title: "...", proposals: [] } },
        },
        errors: ["400 - شناسه نامعتبر", "404 - پروژه یافت نشد"],
      },
      {
        method: "PATCH",
        path: "/project/update/:id",
        title: "بروزرسانی پروژه",
        description: "ویرایش اطلاعات پروژه",
        auth: true,
        role: "OWNER",
        body: { title: "عنوان جدید", budget: 60000000 },
        response: {
          statusCode: 200,
          data: { message: "به روز رسانی انجام شد" },
        },
      },
      {
        method: "PATCH",
        path: "/project/:id",
        title: "تغییر وضعیت پروژه",
        description: "باز یا بسته کردن پروژه",
        auth: true,
        role: "OWNER",
        body: { status: "CLOSED" },
        response: { statusCode: 200, data: { message: "پروژه بسته شد" } },
      },
      {
        method: "DELETE",
        path: "/project/:id",
        title: "حذف پروژه",
        description: "حذف پروژه (فقط اگر فریلنسر انتخاب نشده باشد)",
        auth: true,
        role: "OWNER",
        response: { statusCode: 200, data: { message: "پروژه حذف شد" } },
        errors: ["400 - قابل حذف نیست", "404 - یافت نشد"],
      },
    ],
  },
  {
    category: "💼 پیشنهادها",
    id: "proposal",
    items: [
      {
        method: "GET",
        path: "/proposal/list",
        title: "لیست پیشنهادها",
        description: "دریافت لیست پیشنهادهای فریلنسر",
        auth: true,
        role: "FREELANCER",
        params: "sort (latest/earliest)",
        response: {
          statusCode: 200,
          data: { proposals: [{ _id: "...", price: 45000000, status: 1 }] },
        },
      },
      {
        method: "POST",
        path: "/proposal/add",
        title: "ارسال پیشنهاد",
        description: "ثبت پیشنهاد جدید برای یک پروژه",
        auth: true,
        role: "FREELANCER",
        body: {
          description: "توضیحات پیشنهاد",
          price: 45000000,
          duration: 30,
          projectId: "projectId",
        },
        response: { statusCode: 201, data: { message: "پیشنهاد ایجاد شد" } },
        errors: ["500 - پیشنهاد ثبت نشد"],
      },
      {
        method: "GET",
        path: "/proposal/:id",
        title: "جزئیات پیشنهاد",
        description: "دریافت اطلاعات یک پیشنهاد خاص",
        auth: true,
        response: {
          statusCode: 200,
          data: { proposal: { _id: "...", price: 45000000 } },
        },
        errors: ["400 - شناسه نامعتبر", "404 - یافت نشد"],
      },
      {
        method: "PATCH",
        path: "/proposal/:id",
        title: "تغییر وضعیت پیشنهاد",
        description:
          "تایید یا رد پیشنهاد توسط کارفرما (0: رد، 1: انتظار، 2: تایید)",
        auth: true,
        role: "OWNER",
        body: { status: 2, projectId: "projectId" },
        response: { statusCode: 200, data: { message: "وضعیت تایید شد" } },
        errors: ["500 - آپدیت نشد"],
      },
    ],
  },
  {
    category: "👑 مدیریت (Admin)",
    id: "admin",
    items: [
      {
        method: "POST",
        path: "/admin/category/add",
        title: "افزودن دسته‌بندی",
        description: "ایجاد دسته‌بندی جدید",
        auth: true,
        role: "ADMIN",
        body: {
          title: "برنامه‌نویسی",
          englishTitle: "programming",
          description: "توضیحات",
          type: "main",
        },
        response: { statusCode: 201, data: { message: "دسته بندی افزوده شد" } },
        errors: ["400 - دسته بندی تکراری", "500 - خطای داخلی"],
      },
      {
        method: "PATCH",
        path: "/admin/category/update/:id",
        title: "بروزرسانی دسته‌بندی",
        description: "ویرایش اطلاعات دسته‌بندی",
        auth: true,
        role: "ADMIN",
        body: { title: "عنوان جدید", type: "sub" },
        response: {
          statusCode: 200,
          data: { message: "به روز رسانی انجام شد" },
        },
      },
      {
        method: "DELETE",
        path: "/admin/category/remove/:id",
        title: "حذف دسته‌بندی",
        description: "حذف یک دسته‌بندی",
        auth: true,
        role: "ADMIN",
        response: { statusCode: 200, data: { message: "حذف انجام شد" } },
      },
      {
        method: "GET",
        path: "/admin/user/list",
        title: "لیست کاربران",
        description: "دریافت لیست تمام کاربران سیستم",
        auth: true,
        role: "ADMIN",
        response: {
          statusCode: 200,
          data: { users: [{ _id: "...", name: "علی", role: "FREELANCER" }] },
        },
      },
      {
        method: "PATCH",
        path: "/admin/user/verify/:userId",
        title: "تایید کاربر",
        description: "تایید و فعال‌سازی حساب کاربری",
        auth: true,
        role: "ADMIN",
        response: { statusCode: 200, data: { message: "کاربر تایید شد" } },
      },
      {
        method: "GET",
        path: "/admin/user/profile/:userId",
        title: "پروفایل کاربر",
        description: "دریافت اطلاعات پروفایل یک کاربر خاص",
        auth: true,
        role: "ADMIN",
        response: {
          statusCode: 200,
          data: { user: { _id: "...", name: "علی", email: "ali@example.com" } },
        },
      },
    ],
  },
];
